"""user mod

Revision ID: 5f3bcd1ad958
Revises: e9ee6a4697aa
Create Date: 2023-09-23 20:55:11.760168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3bcd1ad958'
down_revision = 'e9ee6a4697aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        op.alter_column('user', 'id', existing_type=sa.String(length=20), type_=sa.Integer(), postgresql_using='id::integer')
        batch_op.drop_constraint('user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_id_key', ['id'])
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
