"""add processed column

Revision ID: 0152f891d649
Revises: 4840c3e4a55f
Create Date: 2023-11-25 19:44:58.899172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0152f891d649'
down_revision: Union[str, None] = '4840c3e4a55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings_for_scrapping', sa.Column('processed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings_for_scrapping', 'processed')
    # ### end Alembic commands ###
