"""clean up scrape model

Revision ID: 1372fff70575
Revises: 0152f891d649
Create Date: 2023-11-25 20:28:29.717056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1372fff70575'
down_revision: Union[str, None] = '0152f891d649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapped_listing', sa.Column('listing_description', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('posting_body', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('embedding', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('image_links', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('cylinders', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('drive', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('fuel', sa.String(), nullable=True))
    op.add_column('scrapped_listing', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('scrapped_listing', 'odometer',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scrapped_listing', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('scrapped_listing', 'cylinder')
    op.drop_column('scrapped_listing', 'location')
    op.drop_column('scrapped_listing', 'vehicle_type')
    op.drop_column('scrapped_listing', 'link')
    op.drop_column('scrapped_listing', 'description')
    op.drop_column('scrapped_listing', 'description_embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrapped_listing', sa.Column('description_embedding', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scrapped_listing', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scrapped_listing', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scrapped_listing', sa.Column('vehicle_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scrapped_listing', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('scrapped_listing', sa.Column('cylinder', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('scrapped_listing', 'price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('scrapped_listing', 'odometer',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('scrapped_listing', 'url')
    op.drop_column('scrapped_listing', 'fuel')
    op.drop_column('scrapped_listing', 'drive')
    op.drop_column('scrapped_listing', 'cylinders')
    op.drop_column('scrapped_listing', 'image_links')
    op.drop_column('scrapped_listing', 'embedding')
    op.drop_column('scrapped_listing', 'posting_body')
    op.drop_column('scrapped_listing', 'listing_description')
    # ### end Alembic commands ###
