"""add scrape dmodels

Revision ID: 70bbe1647c3f
Revises: 517a6db3a6cd
Create Date: 2023-11-25 15:10:27.969699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bbe1647c3f'
down_revision: Union[str, None] = '517a6db3a6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_craiglist_sites_id', table_name='craiglist_sites')
    op.drop_table('craiglist_sites')
    op.add_column('listings_for_scrapping', sa.Column('link', sa.String(), nullable=True))
    op.add_column('listings_for_scrapping', sa.Column('title', sa.String(), nullable=True))
    op.add_column('listings_for_scrapping', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'listings_for_scrapping', ['link'])
    op.drop_column('listings_for_scrapping', 'listings')
    op.drop_column('listings_for_scrapping', 'search_term')
    op.drop_column('listings_for_scrapping', 'site')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings_for_scrapping', sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('listings_for_scrapping', sa.Column('search_term', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('listings_for_scrapping', sa.Column('listings', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'listings_for_scrapping', type_='unique')
    op.drop_column('listings_for_scrapping', 'date_added')
    op.drop_column('listings_for_scrapping', 'title')
    op.drop_column('listings_for_scrapping', 'link')
    op.create_table('craiglist_sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('site', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='craiglist_sites_pkey')
    )
    op.create_index('ix_craiglist_sites_id', 'craiglist_sites', ['id'], unique=False)
    # ### end Alembic commands ###
