from enum import Enum

#used for response from scrapping
class ScrapeStatus(str, Enum):
    OK = 'ok'
    LISTING_EXPIRED = 'listing expired'
    REQUEST_FAILED = 'request failed'

# all states supported for training a model
class SupportedStates(str, Enum):
    alabama = 'alabama'
    alaska = 'alaska'
    arizona = 'arizona'
    arkansas = 'arkansas'
    california = 'california'
    colorado = 'colorado'
    connecticut = 'connecticut'
    delaware = 'delaware'
    florida = 'florida'
    georgia = 'georgia'
    hawaii = 'hawaii'
    idaho = 'idaho'
    illinois = 'illinois'
    indiana = 'indiana'
    iowa = 'iowa'
    kansas = 'kansas'
    kentucky = 'kentucky'
    louisiana = 'louisiana'
    maine = 'maine'
    maryland = 'maryland'
    massachusetts = 'massachusetts'
    michigan = 'michigan'
    minnesota = 'minnesota'
    mississippi = 'mississippi'
    missouri = 'missouri'
    montana = 'montana'
    nebraska = 'nebraska'
    nevada = 'nevada'
    new_hampshire = 'new hampshire'
    new_jersey = 'new jersey'
    new_mexico = 'new mexico'
    new_york = 'new york'
    north_carolina = 'north carolina'
    north_dakota = 'north dakota'
    ohio = 'ohio'
    oklahoma = 'oklahoma'
    oregon = 'oregon'
    pennsylvania = 'pennsylvania'
    rhode_island = 'rhode island'
    south_carolina = 'south carolina'
    south_dakota = 'south dakota'
    tennessee = 'tennessee'
    texas = 'texas'
    utah = 'utah'
    vermont = 'vermont'
    virginia = 'virginia'
    washington = 'washington'
    west_virginia = 'west virginia'
    wisconsin = 'wisconsin'
    wyoming = 'wyoming'
